package main

import (
	"fmt"
	"math"
	"strings"
)

// Quantization is symmetric per-matrix int8: scale = max|w|/127, q = round(w/scale),
// and w ≈ q*scale on the way back. Each weight/bias matrix carries its own scale.

// QuantVec is one quantized vector plus its reconstruction scale.
type QuantVec struct {
	Q     []int8
	Scale float64
}

// QuantModel is the int8 form of an MLP plus the target normalization needed to
// map the network output back to a raw deep-score prediction.
type QuantModel struct {
	In, Hidden int
	W1         []QuantVec // one per hidden unit (row of In weights)
	B1         QuantVec
	W2         QuantVec
	B2         float64 // scalar bias kept as float (single value; nothing to quantize)
	Mean, Std  float64
}

func quantVec(v []float64) QuantVec {
	max := 0.0
	for _, x := range v {
		if a := math.Abs(x); a > max {
			max = a
		}
	}
	scale := max / 127
	if scale == 0 {
		scale = 1
	}
	q := make([]int8, len(v))
	for i, x := range v {
		r := math.Round(x / scale)
		if r > 127 {
			r = 127
		} else if r < -127 {
			r = -127
		}
		q[i] = int8(r)
	}
	return QuantVec{Q: q, Scale: scale}
}

func (qv QuantVec) at(i int) float64 { return float64(qv.Q[i]) * qv.Scale }

// checkFinite fails if training diverged, leaving Inf/NaN in the model. Without
// this, ExportGo emits e.g. `var B2 float64 = +Inf` or `const Mean = NaN` — valid
// %v output but undefined Go identifiers, so the weights file silently fails to
// compile later (and NaN weights would quantize to a silent 0). Catch it here.
func checkFinite(t *Trained) error {
	bad := func(name string, x float64) error {
		if math.IsInf(x, 0) || math.IsNaN(x) {
			return fmt.Errorf("training diverged: non-finite %s (%v); try a lower -lr", name, x)
		}
		return nil
	}
	m := t.Model
	for h := 0; h < m.Hidden; h++ {
		for _, w := range m.W1[h] {
			if err := bad("W1 weight", w); err != nil {
				return err
			}
		}
		if err := bad("B1 bias", m.B1[h]); err != nil {
			return err
		}
		if err := bad("W2 weight", m.W2[h]); err != nil {
			return err
		}
	}
	if err := bad("B2 bias", m.B2); err != nil {
		return err
	}
	if err := bad("Mean", t.Stats.Mean); err != nil {
		return err
	}
	return bad("Std", t.Stats.Std)
}

// Quantize converts a trained model to its int8 form.
func Quantize(t *Trained) QuantModel {
	m := t.Model
	qm := QuantModel{In: m.In, Hidden: m.Hidden, B2: m.B2, Mean: t.Stats.Mean, Std: t.Stats.Std}
	qm.W1 = make([]QuantVec, m.Hidden)
	for h := 0; h < m.Hidden; h++ {
		qm.W1[h] = quantVec(m.W1[h])
	}
	qm.B1 = quantVec(m.B1)
	qm.W2 = quantVec(m.W2)
	return qm
}

// Predict runs the dequantized forward pass and returns a raw deep-score
// prediction (de-normalized). This is the reference the emitted loader stub
// mirrors and the test round-trips against.
func (qm QuantModel) Predict(x []float64) float64 {
	out := qm.B2
	for h := 0; h < qm.Hidden; h++ {
		z := qm.B1.at(h)
		row := qm.W1[h]
		for i := 0; i < qm.In; i++ {
			z += row.at(i) * x[i]
		}
		out += qm.W2.at(h) * math.Tanh(z)
	}
	return out*qm.Std + qm.Mean
}

// ExportGo renders a QuantModel (from t) as compilable Go source: package vars
// for the int8 weights/scales and normalization, plus a pure-Go forward-pass
// loader stub. The stub is UNUSED BY PRODUCTION — Stage 3 adopts it into the
// int8 inference path inside search.
func ExportGo(t *Trained, pkg string) string {
	qm := Quantize(t)
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/nnue-train; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Int8-quantized NNUE-lite weights (symmetric per-matrix: w ≈ q*scale).\n")
	fmt.Fprintf(&b, "// Layout: input(%d) → hidden(%d, tanh) → 1 (linear).\n", qm.In, qm.Hidden)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import \"math\"\n\n")

	fmt.Fprintf(&b, "const (\n\tInputDim  = %d\n\tHiddenDim = %d\n)\n\n", qm.In, qm.Hidden)
	fmt.Fprintf(&b, "// Score normalization: rawScore = out*Std + Mean.\n")
	fmt.Fprintf(&b, "const (\n\tMean = %v\n\tStd  = %v\n)\n\n", qm.Mean, qm.Std)

	fmt.Fprintf(&b, "// W1 int8 weights, one row (InputDim wide) per hidden unit.\n")
	fmt.Fprintf(&b, "var W1 = [HiddenDim][InputDim]int8{\n")
	for h := 0; h < qm.Hidden; h++ {
		b.WriteString("\t{")
		for i, q := range qm.W1[h].Q {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%d", q)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// W1Scale is the per-row reconstruction scale for W1.\n")
	fmt.Fprintf(&b, "var W1Scale = [HiddenDim]float64{")
	for h := 0; h < qm.Hidden; h++ {
		if h > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%v", qm.W1[h].Scale)
	}
	b.WriteString("}\n\n")

	writeVec := func(name, comment string, qv QuantVec) {
		fmt.Fprintf(&b, "// %s\n", comment)
		fmt.Fprintf(&b, "var %s = [...]int8{", name)
		for i, q := range qv.Q {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%d", q)
		}
		// Explicit float64 type: %v on a whole-number float (e.g. the scale=1
		// zero-guard) prints no decimal point and would otherwise infer int,
		// breaking the loader stub's float arithmetic.
		fmt.Fprintf(&b, "}\nvar %sScale float64 = %v\n\n", name, qv.Scale)
	}
	writeVec("B1", "B1 hidden biases (int8).", qm.B1)
	writeVec("W2", "W2 output weights (int8).", qm.W2)
	fmt.Fprintf(&b, "// B2 output bias (scalar, kept float).\nvar B2 float64 = %v\n\n", qm.B2)

	b.WriteString(loaderStub)
	return b.String()
}

// loaderStub is the pure-Go forward pass emitted alongside the weights. It is
// deliberately self-contained (uses only math.Tanh) so Stage 3 can adopt it
// verbatim into the int8 inference path inside evaluateWithWorkspace.
const loaderStub = `// Predict runs the int8 forward pass and returns a raw deep-score prediction.
//
// UNUSED BY PRODUCTION — this stub exists so Stage 3 (a separate bead) can adopt
// it into the pure-Go int8 inference path inside search's evaluateWithWorkspace.
// Nothing in the current build calls it.
func Predict(x []float64) float64 {
	if len(x) != InputDim {
		panic("nnueweights: input width mismatch")
	}
	out := B2
	for h := 0; h < HiddenDim; h++ {
		z := float64(B1[h]) * B1Scale
		s := W1Scale[h]
		for i := 0; i < InputDim; i++ {
			z += float64(W1[h][i]) * s * x[i]
		}
		out += float64(W2[h]) * W2Scale * mathTanh(z)
	}
	return out*Std + Mean
}

func mathTanh(x float64) float64 { return math.Tanh(x) }
`
